name: Linting

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |-
          cd frontend
          yarn
      - name: Run ESLint
        run: |-
          cd frontend
          yarn lint
